---

- name: Ensure dcos_install.sh is downloaded from bootstrap server
  get_url:
    url: "http://{{ hostvars[groups['bootstrap'][0]]['ansible_bond0_0']['ipv4']['address'] }}:{{ bootstrap_server_port }}/dcos_install.sh"
    dest: /root/dcos_install.sh
    mode: 755
  tags: install-agent

- name: Install DC/OS agents
  shell: /root/dcos_install.sh slave > dcos_install.log
  args:
    creates: /etc/systemd/system/dcos.target
  tags: install-agent
