---

- hosts: masters, agents, pubagents

  gather_facts: True

  tags: facts

- hosts: bootstrap

  roles:
    - role: common
    - role: bootstrap

  tags: bootstrap

  vars_files:
    - vars.yaml

- hosts: masters

  roles:
    - role: common
    - role: master

  vars_files:
    - vars.yaml

- hosts: agents

  roles:
    - role: common
    - role: agent

  vars_files:
    - vars.yaml

- hosts: pubagents

  roles:
    - role: common
    - role: pubagent

  vars_files:
    - vars.yaml
