---

- hosts: all

  vars_files:
    - vars.yaml.example

  tasks:

      - name: Setup IP whitelist firewall
        script: setup_ip_whitelist.sh >> setup_ip_whitelist.log
        tags: firewall,base            
    
      - name: Install Packages
        yum: pkg={{item}} state=installed 
        with_items:
          - ipset
          - tar
          - xz
          - unzip
          - curl
          - docker
        tags: packages,base
        
      - name: Setup Docker overlay storage driver
        copy: src=docker-storage dest=/etc/sysconfig/docker-storage owner=root group=root
        tags: docker,base
        notify:
          - Restart Docker
        changed_when: true
        
      - group:
          name: nogroup
          state: present  
        tags: group,base

      - group:
          name: docker
          state: present
        tags: group, base          
        
  handlers:          
        
      - name: Restart Docker
        systemd:
          name: docker
          enabled: yes
          state: restarted
        tags: docker,base            
        
- hosts: bootstrap            
  roles:
    - role: bootstrap
  tags: bootstrap
  vars_files:
    - vars.yaml.example

- hosts: masters, agents

  tasks:
  
      - name: Download DC/OS install script from bootstrap nginx server
        get_url:
          url: http://{{ hostvars[groups['bootstrap'][0]]['ansible_bond0_0']['ipv4']['address'] }}:{{ bootstrap_server_port }}/dcos_install.sh
          dest: /root/dcos_install.sh
          mode: 755
        tags: download-installer

      - debug:
          msg: "Downloading DC/OS install script from bootstrap nginx server {{ hostvars[groups['bootstrap'][0]]['ansible_bond0_0']['ipv4']['address'] }}:{{ bootstrap_server_port }}/dcos_install.sh"
        tags: download-installer

  vars_files:
    - vars.yaml.example

- hosts: masters

  tasks:
  
      - name: Install DC/OS masters
        shell: /root/dcos_install.sh master
        args:
          creates: /etc/systemd/system/dcos.target      
        tags: install-master
        
- hosts: agents

  tasks:
  
      - name: Install DC/OS masters
        shell: /root/dcos_install.sh slave > dcos_install.log
        args:
          creates: /etc/systemd/system/dcos.target      
        tags: install-agent
        
