---

- hosts: masters, agents

  gather_facts: True

  tags: facts

- hosts: bootstrap

  roles:
    - role: common
    - role: bootstrap

  tags: bootstrap

  vars_files:
    - vars.yaml.example

- hosts: masters

  roles:
    - role: common
    - role: master

  vars_files:
    - vars.yaml.example

- hosts: agents

  roles:
    - role: common
    - role: agent

  vars_files:
    - vars.yaml.example

- hosts: public-agents

  roles:
    - role: common
    - role: public-agent

  vars_files:
    - vars.yaml.example
