---
- hosts: all
  tasks:

      - name: Setup IP whitelist firewall
        script: setup_ip_whitelist.sh >> setup_ip_whitelist.log
        tags: firewall            
    
      - name: Install Packages
        yum: pkg={{item}} state=installed 
        with_items:
          - ipset
          - tar
          - xz
          - unzip
          - curl
        tags: packages

      - name: Uninstall DC/OS
        script: uninstall_dcos.sh >> uninstall_dcos.log        
        tags: uninstall   
            
- hosts: bootstrap            
  tasks:
              
      - name: Setup bootstrap node
        shell: wget 'https://downloads.dcos.io/dcos/stable/commit/0ce03387884523f02624d3fb56c7fbe2e06e181b/dcos_generate_config.sh?ga=2.120260296.1545129356.1499066263-1637564556.1479832876' -O dcos_generate_config.sh
        tags: bootstrap 
        
			
