---
- hosts: all
  tasks:

      - name: Setup IP whitelist firewall
        script: setup_ip_whitelist.sh >> setup_ip_whitelist.log
        tags: firewall            
    
      - name: Install Packages
        yum: pkg={{item}} state=installed 
        with_items:
          - ipset
          - tar
          - xz
          - unzip
          - curl
          - docker
        tags: packages

- hosts: bootstrap            
  roles:
    - role: bootstrap
