---

- hosts: all

  tasks:

      - name: Ensure firewall script is uploaded
        template: src=setup_ip_whitelist.sh.j2 dest=/root/setup_ip_whitelist.sh mode=755 owner=root group=root mode=755
        tags: firewall, base

      - name: Ensure firewall script is executed
        shell: ./setup_ip_whitelist.sh
        tags: firewall, base

      - name: Install Packages
        yum: pkg={{item}} state=installed 
        with_items:
          - ipset
          - tar
          - xz
          - unzip
          - curl
          - docker
        tags: packages,base
        
      - name: Setup Docker overlay storage driver
        copy: src=docker-storage dest=/etc/sysconfig/docker-storage owner=root group=root
        tags: docker,base
        notify:
          - Restart Docker
        changed_when: true
        
      - group:
          name: nogroup
          state: present  
        tags: group,base

      - group:
          name: docker
          state: present
        tags: group, base

  vars_files:
    - vars.yaml.example

  handlers:
        
      - name: Restart Docker
        systemd:
          name: docker
          enabled: yes
          state: restarted
        tags: docker,base            
        
- hosts: bootstrap            
  roles:
    - role: bootstrap
  tags: bootstrap
  vars_files:
    - vars.yaml.example

- hosts: masters, agents

  tasks:
  
      - name: Download DC/OS install script from bootstrap nginx server
        get_url:
          url: "http://{{ hostvars['bootstrap']['ansible_bond0_0']['ipv4']['address'] }}:{{ bootstrap_server_port }}/dcos_install.sh"
          dest: /root/dcos_install.sh
          mode: 755
        tags: download-installer

      - debug:
          msg: "Downloading DC/OS install script from bootstrap nginx server {{ hostvars['bootstrap']['ansible_bond0_0']['ipv4']['address'] }}:{{ bootstrap_server_port }}/dcos_install.sh"
        tags: download-installer

  vars_files:
    - vars.yaml.example

- hosts: masters
  roles:
    - role: master

- hosts: agents

  tasks:
  
      - name: Install DC/OS masters
        shell: /root/dcos_install.sh slave > dcos_install.log
        args:
          creates: /etc/systemd/system/dcos.target      
        tags: install-agent
        
