---
- name: Ensure firewall script is uploaded
  template: src=setup_ip_whitelist.sh.j2 dest=/root/setup_ip_whitelist.sh mode=755 owner=root group=root mode=755
  tags: firewall, common

- name: Ensure firewall script is executed
  shell: ./setup_ip_whitelist.sh
  tags: firewall, common

- name: Install Packages
  yum: pkg={{item}} state=installed
  with_items:
    - ipset
    - tar
    - xz
    - unzip
    - curl
    - docker
  tags: packages, common

- name: Setup Docker overlay storage driver
  copy: src=files/docker-storage dest=/etc/sysconfig/docker-storage owner=root group=root
  tags: docker,base
  notify:
    - Restart Docker
  changed_when: true

- group:
    name: nogroup
    state: present
  tags: group, common

- group:
    name: docker
    state: present
  tags: group, common