---

- name: Add repository
  yum_repository:
    name: extras
    description: EPEL YUM repo
    baseurl: "{{ epel_repo_url }}"
  tags: nginx

- name: Ensure epel-release is installed
  yum: pkg=epel-release state=installed enablerepo=extras   
  tags: nginx

- name: upgrade all packages
  yum: name=* state=latest
  tags: nginx
  when: not ansible_check_mode

- name: Install Packages
  yum: pkg={{item}} state=installed
  with_items:
    - ipset
    - tar
    - xz
    - unzip
    - curl
    - docker
    - jq
  tags: packages, common

- name: Register Packet VPN IP
  shell: "curl -s -X GET --header 'Accept: application/json' --header 'X-Auth-Token: {{ packet_auth_token }}' 'https://api.packet.net/user/vpn?code={{ packet_region }}' | jq -r .config | grep remote | cut -d ' ' -f2 | xargs getent hosts | cut -d ' ' -f1"
  register: packet_vpn_ip
  tags: firewall, common

- name: Ensure ipset script is uploaded
  template: src=templates/setup_ip_whitelist.sh.j2 dest=/root/setup_ip_whitelist.sh mode=755 owner=root group=root mode=755
  tags: firewall, common

- name: Ensure ipset script is executed
  shell: ./setup_ip_whitelist.sh
  tags: firewall, common

- name: Set up IPTables
  iptables_raw:
    name: allow_related
    rules: |
      -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
      -A INPUT -m set ! --match-set whitelist src -j LOG --log-level debug --log-prefix "iptables: "
      -A INPUT -m set ! --match-set whitelist src -j DROP
  tags: firewall, common

- name: Ensure Docker overlay storage driver is configured
  copy: src=files/docker-storage dest=/etc/sysconfig/docker-storage owner=root group=root
  tags: docker, common

- name: Ensure Docker is running
  systemd:
    name: docker
    enabled: yes
    state: started
  tags: docker, common

- group:
    name: nogroup
    state: present
  tags: group, common

- group:
    name: docker
    state: present
  tags: group, common
