---

- name: Ensure dcos_install.sh is downloaded from bootstrap server
  get_url:
    url: "http://{{ hostvars['bootstrap']['ansible_bond0_0']['ipv4']['address'] }}:{{ bootstrap_server_port }}/dcos_install.sh"
    dest: /root/dcos_install.sh
    mode: 755
  tags: install-master

- name: Install DC/OS masters
  shell: /root/dcos_install.sh master
  args:
    creates: /etc/systemd/system/dcos.target
  tags: install-master